// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: collabDiagrameditorService.proto

package collabTexteditorService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollabDiagramEditorService_GenerateDiagram_FullMethodName = "/collabTexteditorService.CollabDiagramEditorService/GenerateDiagram"
)

// CollabDiagramEditorServiceClient is the client API for CollabDiagramEditorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollabDiagramEditorServiceClient interface {
	GenerateDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error)
}

type collabDiagramEditorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollabDiagramEditorServiceClient(cc grpc.ClientConnInterface) CollabDiagramEditorServiceClient {
	return &collabDiagramEditorServiceClient{cc}
}

func (c *collabDiagramEditorServiceClient) GenerateDiagram(ctx context.Context, in *GenerateDiagramRequest, opts ...grpc.CallOption) (*GenerateDiagramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDiagramResponse)
	err := c.cc.Invoke(ctx, CollabDiagramEditorService_GenerateDiagram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollabDiagramEditorServiceServer is the server API for CollabDiagramEditorService service.
// All implementations must embed UnimplementedCollabDiagramEditorServiceServer
// for forward compatibility.
type CollabDiagramEditorServiceServer interface {
	GenerateDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error)
	mustEmbedUnimplementedCollabDiagramEditorServiceServer()
}

// UnimplementedCollabDiagramEditorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollabDiagramEditorServiceServer struct{}

func (UnimplementedCollabDiagramEditorServiceServer) GenerateDiagram(context.Context, *GenerateDiagramRequest) (*GenerateDiagramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDiagram not implemented")
}
func (UnimplementedCollabDiagramEditorServiceServer) mustEmbedUnimplementedCollabDiagramEditorServiceServer() {
}
func (UnimplementedCollabDiagramEditorServiceServer) testEmbeddedByValue() {}

// UnsafeCollabDiagramEditorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollabDiagramEditorServiceServer will
// result in compilation errors.
type UnsafeCollabDiagramEditorServiceServer interface {
	mustEmbedUnimplementedCollabDiagramEditorServiceServer()
}

func RegisterCollabDiagramEditorServiceServer(s grpc.ServiceRegistrar, srv CollabDiagramEditorServiceServer) {
	// If the following call pancis, it indicates UnimplementedCollabDiagramEditorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollabDiagramEditorService_ServiceDesc, srv)
}

func _CollabDiagramEditorService_GenerateDiagram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollabDiagramEditorServiceServer).GenerateDiagram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollabDiagramEditorService_GenerateDiagram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollabDiagramEditorServiceServer).GenerateDiagram(ctx, req.(*GenerateDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollabDiagramEditorService_ServiceDesc is the grpc.ServiceDesc for CollabDiagramEditorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollabDiagramEditorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collabTexteditorService.CollabDiagramEditorService",
	HandlerType: (*CollabDiagramEditorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateDiagram",
			Handler:    _CollabDiagramEditorService_GenerateDiagram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collabDiagrameditorService.proto",
}
