/**
 * @fileoverview gRPC-Web generated client stub for collabTexteditorService
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: collabDiagrameditorService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.collabTexteditorService = require('./collabDiagrameditorService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.collabTexteditorService.CollabDiagramEditorServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.collabTexteditorService.CollabDiagramEditorServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.collabTexteditorService.GenerateDiagramRequest,
 *   !proto.collabTexteditorService.GenerateDiagramResponse>}
 */
const methodDescriptor_CollabDiagramEditorService_GenerateDiagram = new grpc.web.MethodDescriptor(
  '/collabTexteditorService.CollabDiagramEditorService/GenerateDiagram',
  grpc.web.MethodType.UNARY,
  proto.collabTexteditorService.GenerateDiagramRequest,
  proto.collabTexteditorService.GenerateDiagramResponse,
  /**
   * @param {!proto.collabTexteditorService.GenerateDiagramRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.collabTexteditorService.GenerateDiagramResponse.deserializeBinary
);


/**
 * @param {!proto.collabTexteditorService.GenerateDiagramRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.collabTexteditorService.GenerateDiagramResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.collabTexteditorService.GenerateDiagramResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.collabTexteditorService.CollabDiagramEditorServiceClient.prototype.generateDiagram =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/collabTexteditorService.CollabDiagramEditorService/GenerateDiagram',
      request,
      metadata || {},
      methodDescriptor_CollabDiagramEditorService_GenerateDiagram,
      callback);
};


/**
 * @param {!proto.collabTexteditorService.GenerateDiagramRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.collabTexteditorService.GenerateDiagramResponse>}
 *     Promise that resolves to the response
 */
proto.collabTexteditorService.CollabDiagramEditorServicePromiseClient.prototype.generateDiagram =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/collabTexteditorService.CollabDiagramEditorService/GenerateDiagram',
      request,
      metadata || {},
      methodDescriptor_CollabDiagramEditorService_GenerateDiagram);
};


module.exports = proto.collabTexteditorService;

